name: update copyright date

on:
  schedule:
    # At the beginning of every year.
    - cron: "0 0 1 1 *"

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update copyright years
        run: ./update-copyright-date.sh README.md LICENSE
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update copyright year"
          branch: chore/update-copyright-${{ github.run_id }}
          title: "chore: update copyright year"
          body: "Automated annual copyright year update for README.md and LICENSE."
          labels: dependencies
